const textContent = {
    headline_part_1: 'Accounting',
    headline_part_2_words_in_blue: 'made simple',
    headline_part_3: 'for small businesses.',
    subheadline: 'Most bookkeeping software is accurate, but hard to use. We make the opposite trade-off, and hope you don’t get audited.',
    offer: 'Get 6 months free',
    cta: 'Watch video',
    trust_statement: 'Trusted by these six companies so far',
    company_1: 'Transistor',
    company_2: 'Tuple',
    company_3: 'StaticKit',
    company_4: 'Mirage',
    company_5: 'Laravel',
    company_6: 'Statamic',
    feature_headline: 'Everything you need to run your books.',
    feature_subheadline: 'Well everything you need if you aren’t that picky about minor details like tax compliance.',
    feature_1_title: 'Payroll',
    feature_1_description: "Keep track of everyone's salaries and whether or not they've been paid. Direct deposit not supported.",
    feature_2_title: 'Claim expenses',
    feature_2_description: "All of your receipts organized into one place, as long as you don't mind typing in the data by hand.",
    feature_3_title: 'VAT handling',
    feature_3_description: "We only sell our software to companies who don't deal with VAT at all, so technically we do all the VAT stuff they need.",
    feature_4_title: 'Reporting',
    feature_4_description: 'Easily export your data into an Excel spreadsheet where you can do whatever the hell you want with it.',
    cta_headline: 'Get started today',
    cta_subheadline: 'It’s time to take control of your books. Buy our software so you can feel like you’re doing something productive.',
    cta_call_to_action: 'Get 6 months free',
  }